# Glossary Term Metadata Configuration
# This file controls chapter assignments, importance levels, and tags
# for all glossary terms.

metadata_version: '1.0'
description: Glossary term metadata configuration

terms:

  # === Chapter 10 Terms ===
  David Bergey:
    chapter: 10
    exam_importance: medium
    study_importance: medium
    tags: ['Chapter 10']
    notes: ''

  # === Chapter 4 Terms ===
  Enzymes:
    chapter: 4
    exam_importance: medium
    study_importance: medium
    tags: ['biochemistry', 'catalysis', 'proteins', 'metabolism', '']
    notes: ''

  # === Chapter 8 Terms ===
  Proteins:
    chapter: 8
    exam_importance: medium
    study_importance: medium
    tags: []
    notes: ''

  # === Unassigned Terms ===
  Peptide bond:
    chapter: null
    exam_importance: medium
    study_importance: medium
    tags: []
    notes: ''
  Plasmid:
    chapter: null
    exam_importance: medium
    study_importance: medium
    tags: []
    notes: ''
